# Generated by Django 3.2.23 on 2023-11-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('year', models.DecimalField(decimal_places=2, max_digits=50)),
                ('industry', models.CharField(max_length=100)),
                ('size_range', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
            ],
        ),
    ]
