# Generated by Django 3.2.23 on 2023-11-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalyst',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catalyst',
            name='country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catalyst',
            name='domain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catalyst',
            name='industry',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catalyst',
            name='linkedin_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catalyst',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catalyst',
            name='size_range',
            field=models.TextField(),
        ),
    ]
