# Generated by Django 3.2.23 on 2023-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0003_cmiusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmiusers',
            name='username',
            field=models.CharField(default='qwe', max_length=100),
            preserve_default=False,
        ),
    ]
